/**
 * §6/§5 component catalog — one barrel over the per-file inventory in
 * packages/ui/src/components/{primitives,layout,data-display,feedback,forms,charts}.
 * Generated by scripts/generate-doc4-components.py — do not hand-edit.
 */

// primitives (§5.1)
export * from './primitives/AppSelector';
export * from './primitives/Avatar';
export * from './primitives/Badge';
export * from './primitives/Button';
export * from './primitives/Card';
export * from './primitives/Checkbox';
export * from './primitives/CopyButton';
export * from './primitives/Dialog';
export * from './primitives/Divider';
export * from './primitives/EmptyState';
export * from './primitives/ErrorState';
export * from './primitives/Input';
export * from './primitives/Label';
export * from './primitives/LoadingState';
export * from './primitives/Select';
export * from './primitives/Sheet';
export * from './primitives/Slider';
export * from './primitives/Spinner';
export * from './primitives/Switch';
export * from './primitives/Tabs';
export * from './primitives/Textarea';
export * from './primitives/Tooltip';
// layout (§5.2)
export * from './layout/BulkActionBar';
export * from './layout/CodeBlock';
export * from './layout/ConfirmDialog';
export * from './layout/DestructiveConfirmDialog';
export * from './layout/ForbiddenPage';
export * from './layout/Header';
export * from './layout/ImpersonationBanner';
export * from './layout/PageContainer';
export * from './layout/PageHeader';
export * from './layout/Sidebar';
export * from './layout/SidebarItem';
export * from './layout/Topbar';
// data-display (§5.3)
export * from './data-display/DataTable';
export * from './data-display/FormBuilder';
export * from './data-display/ImportCsvDialog';
export * from './data-display/JsonViewer';
export * from './data-display/QrCodeDisplay';
export * from './data-display/RatingStars';
export * from './data-display/RealtimeIndicator';
export * from './data-display/SourceBadge';
export * from './data-display/StatCard';
export * from './data-display/StatusBadge';
export * from './data-display/TagInput';
export * from './data-display/TestimonialCard';
export * from './data-display/TestimonialKanban';
export * from './data-display/WidgetBuilder';
// feedback (§5.4)
export * from './feedback/Alert';
export * from './feedback/ChartCard';
export * from './feedback/NotificationBell';
export * from './feedback/Skeleton';
export * from './feedback/Toast';
export * from './feedback/ToastViewport';
// forms (§5.5)
export * from './forms/ColorPicker';
export * from './forms/FormField';
export * from './forms/FormFileUpload';
export * from './forms/RatingInput';
export * from './forms/RichTextArea';
// charts (§5.6)
export * from './charts/AreaChartCard';
export * from './charts/BarChartCard';
export * from './charts/LineChartCard';
export * from './charts/PieChartCard';

export { ReactQueryProvider, ThemeProviders } from './providers';